# Generated by Django 4.2.30 on 2026-07-05 00:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('latitude_deg', models.FloatField()),
                ('longitude_deg', models.FloatField()),
                ('timezone', models.CharField(help_text='IANA timezone name, e.g. Asia/Jakarta', max_length=64)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PrayerTimeConvention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('fajr_angle_deg', models.FloatField()),
                ('isha_angle_deg', models.FloatField()),
                ('asr_shadow_factor', models.FloatField(default=1.0)),
                ('dhuhr_correction_minutes', models.FloatField(default=2.0)),
                ('is_default', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ConjunctionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hijri_year', models.IntegerField()),
                ('hijri_month', models.IntegerField()),
                ('conjunction_time_utc', models.DateTimeField()),
                ('computed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['hijri_year', 'hijri_month'],
                'unique_together': {('hijri_year', 'hijri_month')},
            },
        ),
        migrations.CreateModel(
            name='VisibilityResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('method', models.CharField(choices=[('wujudul_hilal', 'Wujudul Hilal'), ('mabims_2021', 'MABIMS 2021 (Imkanur Rukyat)'), ('odeh', 'Odeh Criterion')], max_length=32)),
                ('moon_altitude_deg', models.FloatField()),
                ('sun_altitude_deg', models.FloatField()),
                ('elongation_deg', models.FloatField()),
                ('moon_age_hours', models.FloatField()),
                ('illumination_fraction', models.FloatField()),
                ('lag_time_minutes', models.FloatField(null=True)),
                ('verdict', models.CharField(help_text="e.g. 'visible', 'not_visible', or boolean-as-string", max_length=32)),
                ('computed_at', models.DateTimeField(auto_now_add=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visibility_results', to='falak.location')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('location', 'date', 'method')},
            },
        ),
    ]
