# Generated by Django 5.0.14 on 2026-07-06 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('falak', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IsbatRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hijri_year', models.IntegerField()),
                ('hijri_month', models.IntegerField()),
                ('gregorian_start_date', models.DateField(help_text='Actual Kemenag-announced first day of the Hijri month.')),
                ('source_note', models.TextField(help_text='Citation for this date, e.g. Kemenag press release URL/date.')),
                ('verified', models.BooleanField(default=False, help_text='False until a maintainer has confirmed gregorian_start_date against a primary Kemenag source.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-hijri_year', '-hijri_month'],
                'unique_together': {('hijri_year', 'hijri_month')},
            },
        ),
    ]
